apiVersion: v1
kind: ConfigMap
metadata:
  name: ovn-map
  namespace: openstack
data:
  cluster-name: 测试
  config.json: |-
    {
        "node": "ovn-ovsdb-sb-0.ovn-ovsdb-sb.openstack.svc.cluster.local:6642",
        "diylink-test-3": {
            "info": [
                {
                    "IFNAME": "enp3s0f0np0",
                    "pci": "0000:03:00.0",
                    "sriov_numvfs": 127
                },
                {
                    "IFNAME": "enp3s0f1np1",
                    "pci": "0000:03:00.1",
                    "sriov_numvfs": 127
                }
            ],
            "encapip": "10.255.101.3",
            "private_net_nic": "",
            "pub_nic": "bond2.2125"
        },
        "diylink-test-4": {
            "info": [
                {
                    "IFNAME": "enp3s0f0np0",
                    "pci": "0000:03:00.0",
                    "sriov_numvfs": 127
                },
                {
                    "IFNAME": "enp3s0f1np1",
                    "pci": "0000:03:00.1",
                    "sriov_numvfs": 127
                }
            ],
            "encapip": "10.255.101.4",
            "private_net_nic": "",
            "pub_nic": "bond2.2125"
        }
    }

  ovs-status: '0'
 

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vdpa-create
  namespace: openstack
spec:
  selector:
    matchLabels:
      app: diylink-vdpa
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: diylink-vdpa
    spec:
      volumes:
        - name: modules
          hostPath:
            path: /usr/lib/modules
            type: DirectoryOrCreate
        - name: ovs-config
          configMap:
            name: ovn-map
            items:
              - key: config.json
                path: config.json
            defaultMode: 420
      containers:
        - name: vdpa
          image: hub.hitosea.com/diylink/vdpa:v240605
          command:
            - tail
            - '-f'
            - /ovs/create.log
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: OVS_STATUS
              valueFrom:
                configMapKeyRef:
                  name: ovn-map
                  key: ovs-status
            - name: Cluster_Name
              valueFrom:
                configMapKeyRef:
                  name: ovn-map
                  key: cluster-name
          resources:
            limits:
              memory: 2Gi
            requests:
              memory: 1Gi
          volumeMounts:
            - name: modules
              mountPath: /usr/lib/modules
            - name: ovs-config
              mountPath: /ovs/config.json
              subPath: config.json
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add:
                - NET_RAW
              drop:
                - ALL
            privileged: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      dnsPolicy: ClusterFirst
      serviceAccountName: openvswitch-server
      serviceAccount: openvswitch-server
      hostNetwork: true
      securityContext: {}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
                      - ppc64le
                      - s390x
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
      schedulerName: default-scheduler
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  revisionHistoryLimit: 10
