---
manifests:
  deployment_ingress: true
  deployment_error: true
  service_ingress: true
  configmap_ingress_conf: true
  configmap_ingress_etc: true
  service_error: true
conf:
  galera:
    cluster_leader_ttl: 120
endpoints:
  oslo_db:
    hosts:
      default: mariadb
      primary: mariadb-primary-service
...
