---
monitoring:
  prometheus:
    enabled: true
manifests:
  monitoring:
    prometheus:
      configmap_bin: true
      deployment_exporter: true
      job_user_create: true
      secret_etc: true
      service_exporter: true
      network_policy_exporter: true
...
