---
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- job:
    name: openstack-helm-bandit
    roles:
      - zuul: openstack/openstack-helm-infra
      - zuul: zuul/zuul-jobs
    required-projects:
      - openstack/openstack-helm
      - openstack/openstack-helm-infra
    files:
      - ^.*\.py\.tpl$
      - ^.*\.py$
      - ^tools/gate/playbooks/osh-bandit.yaml$
    pre-run: tools/gate/playbooks/prepare-hosts.yaml
    post-run: tools/gate/playbooks/osh-infra-collect-logs.yaml
    run: tools/gate/playbooks/osh-bandit.yaml

- job:
    name: openstack-helm-deploy
    abstract: true
    roles:
      - zuul: openstack/openstack-helm-infra
      - zuul: zuul/zuul-jobs
    required-projects:
      - openstack/openstack-helm
      - openstack/openstack-helm-infra
      - openstack/openstack-helm-plugin
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^releasenotes/.*$
    timeout: 7200
    pre-run:
      - tools/gate/playbooks/prepare-hosts.yaml
    post-run: tools/gate/playbooks/osh-infra-collect-logs.yaml
    run:
      - tools/gate/playbooks/deploy-env.yaml
      - tools/gate/playbooks/run-scripts.yaml
    vars:
      kubeadm:
        pod_network_cidr: "10.244.0.0/24"
        service_cidr: "10.96.0.0/16"
      osh_plugin_repo: "{{ zuul.project.src_dir }}/../openstack-helm-plugin"
      loopback_setup: true
      loopback_device: /dev/loop100
      loopback_image: "/var/lib/openstack-helm/ceph-loop.img"
      ceph_osd_data_device: /dev/loop100
      kube_version_repo: "v1.28"
      kube_version: "1.28.4-1.1"
      calico_version: "v3.27.0"
      helm_version: "v3.6.3"
      yq_version: "v4.6.0"
      crictl_version: "v1.26.1"
      zuul_osh_relative_path: ../openstack-helm
      zuul_osh_infra_relative_path: ../openstack-helm-infra
      gate_scripts_relative_path: ../openstack-helm
      run_helm_tests: "no"
      openstack_provider_gateway_setup: true

- job:
    name: openstack-helm-compute-kit
    parent: openstack-helm-deploy
    abstract: true
    vars:
      gate_scripts:
        - ./tools/deployment/common/prepare-k8s.sh
        - ./tools/deployment/common/prepare-charts.sh
        - ./tools/deployment/common/setup-client.sh
        - ./tools/deployment/common/ingress.sh
        - - ./tools/deployment/component/common/rabbitmq.sh
          - ./tools/deployment/component/common/mariadb.sh
          - ./tools/deployment/component/common/memcached.sh
        - ./tools/deployment/component/keystone/keystone.sh
        - - ./tools/deployment/component/heat/heat.sh
          - export GLANCE_BACKEND=memory; ./tools/deployment/component/glance/glance.sh
          - ./tools/deployment/component/compute-kit/openvswitch.sh
        - ./tools/deployment/component/compute-kit/libvirt.sh
        - ./tools/deployment/component/compute-kit/compute-kit.sh
        - export OSH_TEST_TIMEOUT=1200;./tools/deployment/common/run-helm-tests.sh neutron
        - ./tools/deployment/common/run-helm-tests.sh nova
        - ./tools/deployment/common/run-helm-tests.sh glance
        - ./tools/deployment/common/run-helm-tests.sh keystone
        - ./tools/deployment/common/use-it.sh
        - ./tools/deployment/common/force-cronjob-run.sh

- job:
    name: openstack-helm-compute-kit-helm-repo-local
    parent: openstack-helm-deploy
    abstract: true
    vars:
      osh_helm_repo: openstack-helm
      osh_infra_helm_repo: openstack-helm-infra
      gate_scripts:
        - ./tools/deployment/common/prepare-k8s.sh
        - ./tools/deployment/common/prepare-charts.sh
        - ./tools/deployment/common/prepare-helm-repos-local.sh
        - ./tools/deployment/common/setup-client.sh
        - ./tools/deployment/common/ingress.sh
        - - ./tools/deployment/component/common/rabbitmq.sh
          - ./tools/deployment/component/common/mariadb.sh
          - ./tools/deployment/component/common/memcached.sh
        - ./tools/deployment/component/keystone/keystone.sh
        - - ./tools/deployment/component/heat/heat.sh
          - export GLANCE_BACKEND=memory; ./tools/deployment/component/glance/glance.sh
          - ./tools/deployment/component/compute-kit/openvswitch.sh
        - ./tools/deployment/component/compute-kit/libvirt.sh
        - ./tools/deployment/component/compute-kit/compute-kit.sh
        - export OSH_TEST_TIMEOUT=1200;./tools/deployment/common/run-helm-tests.sh neutron
        - ./tools/deployment/common/run-helm-tests.sh nova
        - ./tools/deployment/common/run-helm-tests.sh glance
        - ./tools/deployment/common/run-helm-tests.sh keystone
        - ./tools/deployment/common/use-it.sh
        - ./tools/deployment/common/force-cronjob-run.sh

- job:
    name: openstack-helm-compute-kit-helm-repo-public
    parent: openstack-helm-deploy
    abstract: true
    vars:
      osh_helm_repo: openstack-helm
      osh_infra_helm_repo: openstack-helm-infra
      download_overrides: "-d"
      gate_scripts:
        - ./tools/deployment/common/prepare-k8s.sh
        - ./tools/deployment/common/prepare-charts.sh
        - ./tools/deployment/common/prepare-helm-repos-public.sh
        - ./tools/deployment/common/setup-client.sh
        - ./tools/deployment/common/ingress.sh
        - - ./tools/deployment/component/common/rabbitmq.sh
          - ./tools/deployment/component/common/mariadb.sh
          - ./tools/deployment/component/common/memcached.sh
        - ./tools/deployment/component/keystone/keystone.sh
        - - ./tools/deployment/component/heat/heat.sh
          - export GLANCE_BACKEND=memory; ./tools/deployment/component/glance/glance.sh
          - ./tools/deployment/component/compute-kit/openvswitch.sh
        - ./tools/deployment/component/compute-kit/libvirt.sh
        - ./tools/deployment/component/compute-kit/compute-kit.sh
        - export OSH_TEST_TIMEOUT=1200;./tools/deployment/common/run-helm-tests.sh neutron
        - ./tools/deployment/common/run-helm-tests.sh nova
        - ./tools/deployment/common/run-helm-tests.sh glance
        - ./tools/deployment/common/run-helm-tests.sh keystone
        - ./tools/deployment/common/use-it.sh
        - ./tools/deployment/common/force-cronjob-run.sh

- job:
    name: openstack-helm-compute-kit-ovn
    parent: openstack-helm-deploy
    abstract: true
    vars:
      gate_scripts:
        - ./tools/deployment/common/prepare-k8s.sh
        - ./tools/deployment/common/prepare-charts.sh
        - ./tools/deployment/common/setup-client.sh
        - ./tools/deployment/common/ingress.sh
        - - ./tools/deployment/component/common/rabbitmq.sh
          - ./tools/deployment/component/common/mariadb.sh
          - ./tools/deployment/component/common/memcached.sh
        - ./tools/deployment/component/keystone/keystone.sh
        - - ./tools/deployment/component/heat/heat.sh
          - export GLANCE_BACKEND=memory; ./tools/deployment/component/glance/glance.sh
        - ./tools/deployment/component/compute-kit/openvswitch.sh
        - ./tools/deployment/component/compute-kit/libvirt.sh
        - ./tools/deployment/component/ovn/ovn.sh
        - ./tools/deployment/component/compute-kit/compute-kit.sh
        - export OSH_TEST_TIMEOUT=1200;./tools/deployment/common/run-helm-tests.sh neutron
        - ./tools/deployment/common/run-helm-tests.sh nova
        - ./tools/deployment/common/run-helm-tests.sh glance
        - ./tools/deployment/common/run-helm-tests.sh keystone
        - ./tools/deployment/common/use-it.sh
        - ./tools/deployment/common/force-cronjob-run.sh

- job:
    name: openstack-helm-keystone-ldap
    parent: openstack-helm-deploy
    abstract: true
    files:
      - ^keystone/.*$
      - ^zuul\.d/.*$
    vars:
      gate_scripts:
        - ./tools/deployment/common/prepare-k8s.sh
        - ./tools/deployment/common/prepare-charts.sh
        - ./tools/deployment/common/setup-client.sh
        - ./tools/deployment/common/cert-manager.sh
        - ./tools/deployment/common/ingress.sh
        - ./tools/deployment/component/common/mariadb.sh
        - ./tools/deployment/component/common/memcached.sh
        - ./tools/deployment/component/common/rabbitmq.sh
        - ./tools/deployment/component/common/ldap.sh
        - ./tools/deployment/component/keystone/keystone.sh

- job:
    name: openstack-helm-cinder
    parent: openstack-helm-deploy
    abstract: true
    files:
      - ^cinder/.*$
      - ^zuul\.d/.*$
      - ^tools/deployment/component/cinder/.
    vars:
      gate_scripts:
        - ./tools/deployment/common/prepare-k8s.sh
        - ./tools/deployment/common/prepare-charts.sh
        - ./tools/deployment/common/setup-client.sh
        - ./tools/deployment/component/ceph/ceph.sh
        - ./tools/deployment/component/ceph/ceph-ns-activate.sh
        - ./tools/deployment/common/ingress.sh
        - - ./tools/deployment/component/common/mariadb.sh
          - ./tools/deployment/component/common/memcached.sh
          - ./tools/deployment/component/common/rabbitmq.sh
        - ./tools/deployment/component/keystone/keystone.sh
        - ./tools/deployment/component/cinder/cinder.sh
        - ./tools/deployment/common/force-cronjob-run.sh

- job:
    name: openstack-helm-cinder-rook
    parent: openstack-helm-deploy
    abstract: true
    files:
      - ^cinder/.*$
      - ^zuul\.d/.*$
      - ^tools/deployment/component/cinder/.
    vars:
      gate_scripts:
        - ./tools/deployment/common/prepare-k8s.sh
        - ./tools/deployment/common/prepare-charts.sh
        - ./tools/deployment/common/setup-client.sh
        - ./tools/deployment/component/ceph/ceph-rook.sh
        - ./tools/deployment/component/ceph/ceph-adapter-rook.sh
        - ./tools/deployment/common/ingress.sh
        - - ./tools/deployment/component/common/mariadb.sh
          - ./tools/deployment/component/common/memcached.sh
          - ./tools/deployment/component/common/rabbitmq.sh
        - ./tools/deployment/component/keystone/keystone.sh
        - ./tools/deployment/component/cinder/cinder.sh
        - ./tools/deployment/common/force-cronjob-run.sh

- job:
    name: openstack-helm-umbrella
    parent: openstack-helm-deploy
    abstract: true
    files:
      - ^glance/.*$
      - ^heat/.*$
      - ^horizon/.*$
      - ^keystone/.*$
      - ^neutron/.*$
      - ^nova/.*$
      - ^openstack/.*$
      - ^placement/.*$
      - ^tools/deployment/common/force-cronjob-run.sh$
      - ^tools/deployment/common/setup-client.sh$
      - ^tools/deployment/component/common/openstack.sh$
      - ^tools/deployment/common/use-it.sh$
      - ^tools/deployment/common/validate-umbrella-upgrade-no-side-effects.sh$
      - ^tools/deployment/common/validate-umbrella-upgrade-config-changes-do-not-update-other-components.sh$
      - ^zuul\.d/.*$
    vars:
      run_helm_tests: "yes"
      gate_scripts:
        - ./tools/deployment/common/prepare-k8s.sh
        - ./tools/deployment/common/prepare-charts.sh
        - ./tools/deployment/common/setup-client.sh
        - ./tools/deployment/common/ingress.sh
        - export GLANCE_BACKEND=memory; ./tools/deployment/component/common/openstack.sh
        - - ./tools/deployment/common/use-it.sh
          - ./tools/deployment/common/force-cronjob-run.sh
        - ./tools/deployment/common/validate-umbrella-upgrade-no-side-effects.sh
        - ./tools/deployment/common/validate-umbrella-upgrade-config-changes-do-not-update-other-components.sh

- job:
    name: openstack-helm-horizon
    parent: openstack-helm-deploy
    abstract: true
    files:
      - ^horizon/.*$
      - ^zuul\.d/.*$
      - ^tools/deployment/component/horizon/.*$
    vars:
      gate_scripts:
        - ./tools/deployment/common/prepare-k8s.sh
        - ./tools/deployment/common/prepare-charts.sh
        - ./tools/deployment/common/setup-client.sh
        - ./tools/deployment/common/ingress.sh
        - ./tools/deployment/component/common/mariadb.sh
        - ./tools/deployment/component/common/memcached.sh
        - ./tools/deployment/component/common/rabbitmq.sh
        - ./tools/deployment/component/keystone/keystone.sh
        - ./tools/deployment/component/horizon/horizon.sh

- job:
    name: openstack-helm-tls
    parent: openstack-helm-deploy
    abstract: true
    vars:
      gate_scripts:
        - ./tools/deployment/common/prepare-k8s.sh
        - ./tools/deployment/common/prepare-charts.sh
        - ./tools/deployment/common/setup-client.sh
        - ./tools/deployment/common/cert-manager.sh
        - ./tools/deployment/component/ceph/ceph.sh
        - ./tools/deployment/component/ceph/ceph-ns-activate.sh
        - ./tools/deployment/common/ingress.sh
        - - ./tools/deployment/component/common/mariadb.sh
          - ./tools/deployment/component/common/memcached.sh
          - ./tools/deployment/component/common/rabbitmq.sh
        - ./tools/deployment/component/keystone/keystone.sh
        - - ./tools/deployment/component/cinder/cinder.sh
          - ./tools/deployment/component/heat/heat.sh
          - export GLANCE_BACKEND=memory; ./tools/deployment/component/glance/glance.sh
          - ./tools/deployment/component/compute-kit/openvswitch.sh
        - ./tools/deployment/component/compute-kit/libvirt.sh
        - ./tools/deployment/component/compute-kit/compute-kit.sh
        - - export OSH_TEST_TIMEOUT=1200;./tools/deployment/common/run-helm-tests.sh neutron
          - ./tools/deployment/common/run-helm-tests.sh nova;
            ./tools/deployment/common/run-helm-tests.sh glance;
            ./tools/deployment/common/run-helm-tests.sh keystone;
            ./tools/deployment/common/run-helm-tests.sh cinder;
        - - ./tools/deployment/common/use-it.sh
          - ./tools/deployment/common/force-cronjob-run.sh

- job:
    name: openstack-helm-tungsten-fabric
    parent: openstack-helm-deploy
    abstract: true
    timeout: 9600
    vars:
      gate_scripts:
        - ./tools/deployment/common/prepare-k8s.sh
        - ./tools/deployment/common/prepare-charts.sh
        - ./tools/deployment/common/setup-client.sh
        - ./tools/deployment/common/ingress.sh
        - - ./tools/deployment/component/common/mariadb.sh
          - ./tools/deployment/component/common/memcached.sh
          - ./tools/deployment/component/common/rabbitmq.sh
        - - ./tools/deployment/component/compute-kit/tungsten-fabric.sh checkdns
          - ./tools/deployment/component/compute-kit/tungsten-fabric.sh setupdns
          - ./tools/deployment/component/keystone/keystone.sh
        - - ./tools/deployment/component/heat/heat.sh
          - export GLANCE_BACKEND=memory; ./tools/deployment/component/glance/glance.sh
          - ./tools/deployment/component/compute-kit/tungsten-fabric.sh prepare
          - ./tools/deployment/component/compute-kit/libvirt.sh
        - ./tools/deployment/component/compute-kit/compute-kit.sh
        - ./tools/deployment/component/compute-kit/tungsten-fabric.sh deploy

- job:
    name: openstack-helm-netpol-compute-kit
    parent: openstack-helm-deploy
    abstract: true
    timeout: 7200
    vars:
      osh_params:
        openstack_release: "2023.1"
        container_distro_name: ubuntu
        container_distro_version: focal
        feature_gates: netpol
      gate_scripts:
        - ./tools/deployment/common/prepare-k8s.sh
        - ./tools/deployment/common/prepare-charts.sh
        - ./tools/deployment/common/setup-client.sh
        - ./tools/deployment/common/ingress.sh
        - ./tools/deployment/common/lockdown-netpol.sh
        - ./tools/deployment/component/common/mariadb.sh
        - ./tools/deployment/component/common/memcached.sh
        - ./tools/deployment/component/common/rabbitmq.sh
        - ./tools/deployment/component/keystone/keystone.sh
        - ./tools/deployment/component/heat/heat.sh
        - export GLANCE_BACKEND=memory; ./tools/deployment/component/glance/glance.sh
        - ./tools/deployment/component/compute-kit/openvswitch.sh
        - ./tools/deployment/component/compute-kit/libvirt.sh
        - ./tools/deployment/component/compute-kit/compute-kit.sh
        - ./tools/deployment/component/horizon/horizon.sh
        - ./tools/deployment/common/openstack-exporter.sh
        - ./tools/deployment/common/use-it.sh
        - ./tools/deployment/common/test-networkpolicy.sh

- job:
    name: openstack-helm-netpol-cinder
    parent: openstack-helm-deploy
    abstract: true
    timeout: 7200
    vars:
      osh_params:
        openstack_release: "2023.1"
        container_distro_name: ubuntu
        container_distro_version: focal
        feature_gates: netpol
      gate_scripts:
        - ./tools/deployment/common/prepare-k8s.sh
        - ./tools/deployment/common/prepare-charts.sh
        - ./tools/deployment/common/setup-client.sh
        - ./tools/deployment/component/ceph/ceph.sh
        - ./tools/deployment/component/ceph/ceph-ns-activate.sh
        - ./tools/deployment/common/lockdown-netpol.sh
        - ./tools/deployment/common/ingress.sh
        - ./tools/deployment/component/common/mariadb.sh
        - ./tools/deployment/component/common/memcached.sh
        - ./tools/deployment/component/common/rabbitmq.sh
        - ./tools/deployment/component/keystone/keystone.sh
        - ./tools/deployment/component/cinder/cinder.sh
        - ./tools/deployment/component/horizon/horizon.sh
        - ./tools/deployment/common/openstack-exporter.sh
        - ./tools/deployment/common/test-networkpolicy.sh

- job:
    name: openstack-helm-tacker
    parent: openstack-helm-deploy
    abstract: true
    timeout: 7200
    vars:
      gate_scripts:
        - ./tools/deployment/common/prepare-k8s.sh
        - ./tools/deployment/common/prepare-charts.sh
        - ./tools/deployment/common/setup-client.sh
        - ./tools/deployment/common/ingress.sh
        - - ./tools/deployment/component/common/rabbitmq.sh
          - ./tools/deployment/component/common/mariadb.sh
          - ./tools/deployment/component/common/memcached.sh
        - ./tools/deployment/component/keystone/keystone.sh
        - - ./tools/deployment/component/heat/heat.sh
          - export GLANCE_BACKEND=memory; ./tools/deployment/component/glance/glance.sh
          - ./tools/deployment/component/compute-kit/openvswitch.sh
        - ./tools/deployment/component/compute-kit/libvirt.sh
        - ./tools/deployment/component/compute-kit/compute-kit.sh
        - ./tools/deployment/component/barbican/barbican.sh
        - ./tools/deployment/component/nfs-provisioner/nfs-provisioner.sh
        - ./tools/deployment/component/tacker/tacker.sh
